version: '3'
services:
    web:
        image: nginx:alpine
        container_name: docker-nginx
        volumes:
            - "./front-end/etc/nginx:/etc/nginx/conf.d"
            - "./front-end/etc/ssl:/etc/ssl"
            - "./front-end/web:/var/www/html"
        ports:
            - "8000:80"
            - "8011:8001"
            - "8022:8002"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        # command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on: 
            - app-pm2
    app-pm2: 
        container_name: app-pm2
        build: ./back-end
        # working_dir: /var/www/back-end
        # command: ["npm run dev"]
        ports:
            - "3000:3001"